#!/usr/bin/env ruby
require 'pangu'
# before use this,be sure that you have 'gem install pangu'

puts ARGV
ARGV.each { |fn|
  content=Pangu.spacing(File.read(fn))
 File.open(fn,'w+') {|f| f.write(content)}
}
