#!/usr/bin/env bash

music_dir=~/Music
music_count=$( ls -1 ${music_dir}|wc -l )
work_time=2400
rest_time=600
flag=0

show(){
  DISPLAY=0:0 XAUTHORITY=~/.Xauthority notify-send "$1"
}
play(){
  cur_time=`date "+%s"`
  trap "exit" INT # Without this,you can't stop by precc ctrl+c.Useful when test from terminal
  while [ $((`date "+%s"`-${cur_time})) -lt ${rest_time}  ];do
    random_idx=$(( ( RANDOM % ${music_count} )  + 1 ))
    music_to_play="`ls -1 ${music_dir}|sed -n \"${random_idx} p\"`"
    show "${music_to_play}"
    echo "${music_to_play}"> /tmp/music_to_play
    mplayer ${music_dir}/"${music_to_play}" &>/tmp/mplayer.log
  done
}
relax(){
  play &
  play_pid=$!
  sleep ${rest_time}
  mplayer_pid=`ps -ef|grep ${play_pid}|grep mplayer|awk '{print $2}'`
  echo ${mplayer_pid}>/tmp/rest_mplayer_id
  kill ${mplayer_pid}
}

clean(){
  pgrep -f rest|
  while read pid
  do
    [ $$ -gt ${pid} ] && kill $pid
  done
  echo 'alive'
}

begin(){
  clean
  [ -e ‘/tmp/rest_mplayer_id’ ] && kill `</tmp/rest_mplayer_id`
  while [ ${flag} -eq 0 ];
  do
    echo work time
    show "Work time"
    sleep ${work_time}
    show "Take a rest will be better."
    echo rest time
    relax
  done
}

case $1 in
  *)
    begin &
    ;;
esac
